In [28]:

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import csv
import seaborn as sns

In [29]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [30]:
dispo = pd.read_csv('./sources/DisponibiliteAlimentaire_2017.csv')
pop = pd.read_csv('./sources/Population_2000_2018.csv')
pib = pd.read_csv('./sources/pib.csv')
stab = pd.read_csv('./sources/stabilite.csv')
dispo_2013 = pd.read_csv('./sources/dispo_volailles_2013.csv')
iso3 = pd.read_csv('./sources/countries-codes.csv', sep=';')

In [31]:
# On ne garde que la quantité d'importation  et la disponibilité interieur de  volail par pays pour 2017 et 2013
poultry = dispo[dispo['Code Produit']==2734]
poultry.nunique()

display(poultry[:10])

importation2017 = pd.pivot(data=poultry, index="Zone",columns=["Élément"], values=["Valeur"])
importation2017= importation2017.Valeur[["Disponibilité intérieure","Importations - Quantité", "Disponibilité de protéines en quantité (g/personne/jour)"]]
#dispo2013 = pd.pivot(data=dispo_2013,index="Zone", columns=["Élément"], values=["Valeur"])
display(importation2017.info())
#dispo2013.rename(columns={"Disponibilité alimentaire (Kcal/personne/jour)": "Disponibilité alimentaire (Kcal/personne/jour) 2013",
 #               "Disponibilité intérieure": "Disponibilité intérieure 2013", "Importations - Quantité": "Importations - Quantité2013"}, inplace=True)
#dispo2013 = dispo2013.Valeur[["Disponibilité intérieure 2013","Importations - Quantité2013"]]

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
651,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5511,Production,2734,Viande de Volailles,2017,2017,Milliers de tonnes,28.00,S,Données standardisées
652,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5611,Importations - Quantité,2734,Viande de Volailles,2017,2017,Milliers de tonnes,29.00,S,Données standardisées
653,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5072,Variation de stock,2734,Viande de Volailles,2017,2017,Milliers de tonnes,0.00,S,Données standardisées
654,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5301,Disponibilité intérieure,2734,Viande de Volailles,2017,2017,Milliers de tonnes,57.00,S,Données standardisées
655,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5123,Pertes,2734,Viande de Volailles,2017,2017,Milliers de tonnes,2.00,S,Données standardisées
656,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5170,Résidus,2734,Viande de Volailles,2017,2017,Milliers de tonnes,0.00,S,Données standardisées
657,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5142,Nourriture,2734,Viande de Volailles,2017,2017,Milliers de tonnes,55.00,S,Données standardisées
658,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2734,Viande de Volailles,2017,2017,kg,1.53,Fc,Donnée calculée
659,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,664,Disponibilité alimentaire (Kcal/personne/jour),2734,Viande de Volailles,2017,2017,Kcal/personne/jour,5.00,Fc,Donnée calculée
660,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,674,Disponibilité de protéines en quantité (g/pers...,2734,Viande de Volailles,2017,2017,g/personne/jour,0.54,Fc,Donnée calculée

<class 'pandas.core.frame.DataFrame'>
Index: 172 entries, Afghanistan to Îles Salomon
Data columns (total 3 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   Disponibilité intérieure                                  170 non-null    float64
 1   Importations - Quantité                                   170 non-null    float64
 2   Disponibilité de protéines en quantité (g/personne/jour)  172 non-null    float64
dtypes: float64(3)
memory usage: 5.4+ KB

None

In [32]:
#complete = pd.merge(left=importation2017, right=dispo2013, on='Zone', how='left')
#display(poultry)
#omplete= complete.drop()

In [33]:
# Calcul des taux d'évolutions d'importation et de disponibilité entre 2013 et 1017 
#complete['Ratio importation volailles / disponibilité interieure volailles 2013'] = complete['Importations - Quantité2013'] / complete['Disponibilité intérieure 2013']
complete = importation2017
display(complete[:5])
complete['Ratio importation volailles / disponibilité interieure volailles 2017'] = complete['Importations - Quantité'] / complete['Disponibilité intérieure']
#complete['Evo importations volailles'] = (complete['Importations - Quantité'] - complete['Importations - Quantité2013']) / (complete['Importations - Quantité2013'] + 0.00001)
#complete['Evo disponibilité intérieure'] = (complete['Disponibilité intérieure'] - complete['Disponibilité intérieure 2013']) / complete['Disponibilité intérieure 2013']
#complete['Evo ratio importation volailles / disponibilité interieure volailles'] = (complete['Ratio importation volailles / disponibilité interieure volailles 2017'] - complete['Ratio importation volailles / disponibilité interieure volailles 2013']) / (complete['Ratio importation volailles / disponibilité interieure volailles 2013'] + 0.000001)
#complete = complete.drop(['Importations - Quantité2013', 'Disponibilité intérieure 2013', 'Ratio importation volailles / disponibilité interieure volailles 2013'], axis=1)
complete = complete.rename(columns={'Disponibilité intérieure': 'Disponibilité intérieure volailles', 'Ratio importation volailles / disponibilité interieure volailles 2017': 'Ratio importation volailles / disponibilité interieure volailles'})
#complete.info()'''
display(complete[:1])
#display(complete.isna()== "True")
complete= complete.dropna()
complete.shape

Élément,Disponibilité intérieure,Importations - Quantité,Disponibilité de protéines en quantité (g/personne/jour)
Zone,,,
Afghanistan,57.0,29.0,0.54
Afrique du Sud,2118.0,514.0,14.11
Albanie,47.0,38.0,6.26
Algérie,277.0,2.0,1.97
Allemagne,1739.0,842.0,7.96

Élément,Disponibilité intérieure volailles,Importations - Quantité,Disponibilité de protéines en quantité (g/personne/jour),Ratio importation volailles / disponibilité interieure volailles
Zone,,,,
Afghanistan,57.0,29.0,0.54,0.508772

(170, 4)

### Fichier population

In [34]:
#Recuperation des valeurs de population pour 2013 et 2017
pop2013 = pop.loc[pop['Année']==2013,['Zone','Valeur']]
pop2017 = pop.loc[pop['Année']==2017,['Zone','Valeur']]

In [35]:
pop = pd.merge(pop2013, pop2017, on='Zone', how='inner')
pop.rename(columns={'Valeur_x' : 'Population 2013', 'Valeur_y' : 'Population 2017'}, inplace=True)
#display( pop[:1])
pop.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 236 entries, 0 to 235
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Zone             236 non-null    object
 1   Population 2013  236 non-null    float64
 2   Population 2017  236 non-null    float64
dtypes: float64(2), object(1)
memory usage: 7.4+ KB

In [36]:
# Calcul de l'evalution de la populatioin entre 2013 et 2017
pop['Pop_evo'] = (pop['Population 2017'] - pop['Population 2013']) / pop['Population 2013']
pop['Population 2017'] = pop['Population 2017'] * 1000
pop.drop(labels='Population 2013', inplace=True, axis=1)
display(pop[:5])

             Zone  Population 2017   Pop_evo
0     Afghanistan       36296113.0  0.124778
1  Afrique du Sud       57009756.0  0.061889
2         Albanie        2884169.0 -0.006757
3         Algérie       41389189.0  0.085187
4       Allemagne       82658409.0  0.018282

In [37]:
# Fusion avec le Data Frame final
complete = pd.merge(left= complete, right= pop, on='Zone', how='inner')

display(complete[:1])
complete.info()

,Zone,Disponibilité intérieure volailles,Importations - Quantité,Disponibilité de protéines en quantité (g/personne/jour),Ratio importation volailles / disponibilité interieure volailles,Population 2017,Pop_evo
0,Afghanistan,57.0,29.0,0.54,0.508772,36296113.0,0.124778

<class 'pandas.core.frame.DataFrame'>
Int64Index: 170 entries, 0 to 169
Data columns (total 7 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Zone                                                              170 non-null    object
 1   Disponibilité intérieure volailles                                170 non-null    float64
 2   Importations - Quantité                                           170 non-null    float64
 3   Disponibilité de protéines en quantité (g/personne/jour)          170 non-null    float64
 4   Ratio importation volailles / disponibilité interieure volailles  170 non-null    float64
 5   Population 2017                                                   170 non-null    float64
 6   Pop_evo                                                           170 non-null    float64
dtypes: float64(6), object(1)
memory usage: 10.6+ KB

### Fichier PIB

In [38]:
# Recuperation des valeur de pib pour 2013 et 2017
pib2013 = pib.loc[pib['Année'] == 2013, ['Zone', 'Valeur']]
pib2017 = pib.loc[pib['Année'] == 2017, ['Zone', 'Valeur']]

pib = pd.merge(pib2013, pib2017, on='Zone', how='inner')
pib.rename(columns={'Valeur_x' : 'pib 2013', 'Valeur_y' : 'pib 2017'}, inplace=True)

In [39]:
# Calcul du taux d'evolution du pib
pib['Evolution pib'] = (pib['pib 2017'] - pib['pib 2013']) / pib['pib 2013']
pib = pib[['Zone','pib 2017', 'Evolution pib']]
display(pib[:1])

          Zone  pib 2017  Evolution pib
0  Afghanistan    2058.4      -0.027451

In [40]:
complete = pd.merge(left= complete, right= pib, on='Zone', how='inner')
display(complete[:1])
#complete.info()

,Zone,Disponibilité intérieure volailles,Importations - Quantité,Disponibilité de protéines en quantité (g/personne/jour),Ratio importation volailles / disponibilité interieure volailles,Population 2017,Pop_evo,pib 2017,Evolution pib
0,Afghanistan,57.0,29.0,0.54,0.508772,36296113.0,0.124778,2058.4,-0.027451

In [41]:
#Recuperation des valeurs de stabilité politique pour 2013 et 2017

#stab2013 = stab.loc[stab['Année']==2013,['Zone','Valeur']]
stab = stab.loc[stab['Année']==2017,['Zone','Valeur']]

#stab = pd.merge(stab2013, stab2017, on='Zone', how='inner')

stab.rename(columns={'Valeur' :  'Stabilité 2017'}, inplace=True)
display(stab[:1])

           Zone  Stabilité 2017
16  Afghanistan            -2.8

In [42]:
#tab['Evolution stab'] = (stab['Stabilité 2017']) - (stab['Stab 2013']) / abs(stab['Stab 2013'])
stab = stab[['Zone','Stabilité 2017']]
display(stab[:1])

           Zone  Stabilité 2017
16  Afghanistan            -2.8

In [43]:
complete = pd.merge(left= complete, right= stab, on='Zone', how='inner')
complete = complete.dropna(axis=0)
complete.drop(labels= 48, axis=0, inplace=True )
complete.info()
#display(complete)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 161 entries, 0 to 161
Data columns (total 10 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Zone                                                              161 non-null    object
 1   Disponibilité intérieure volailles                                161 non-null    float64
 2   Importations - Quantité                                           161 non-null    float64
 3   Disponibilité de protéines en quantité (g/personne/jour)          161 non-null    float64
 4   Ratio importation volailles / disponibilité interieure volailles  161 non-null    float64
 5   Population 2017                                                   161 non-null    float64
 6   Pop_evo                                                           161 non-null    float64
 7   pib 2017                                                          161 non-null    float64
 8   Evolution pib                                                     161 non-null    float64
 9   Stabilité 2017                                                    161 non-null    float64
dtypes: float64(9), object(1)
memory usage: 13.8+ KB

In [44]:
complete.info()
complete = complete.to_csv("complete_df.csv", index=False)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 161 entries, 0 to 161
Data columns (total 10 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Zone                                                              161 non-null    object
 1   Disponibilité intérieure volailles                                161 non-null    float64
 2   Importations - Quantité                                           161 non-null    float64
 3   Disponibilité de protéines en quantité (g/personne/jour)          161 non-null    float64
 4   Ratio importation volailles / disponibilité interieure volailles  161 non-null    float64
 5   Population 2017                                                   161 non-null    float64
 6   Pop_evo                                                           161 non-null    float64
 7   pib 2017                                                          161 non-null    float64
 8   Evolution pib                                                     161 non-null    float64
 9   Stabilité 2017                                                    161 non-null    float64
dtypes: float64(9), object(1)
memory usage: 13.8+ KB